# Generated by Django 4.2.7 on 2026-04-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_marks', models.IntegerField(default=0)),
                ('practical_marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.subject')),
            ],
            options={
                'db_table': 'marks',
                'unique_together': {('student', 'course', 'academic_year')},
            },
        ),
    ]
